# Generated by Django 2.2.6 on 2019-10-22 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=200, verbose_name='Nombre del Producto')),
                ('TipoProducto', models.IntegerField(choices=[(0, 'Hardware'), (1, 'Software')], default=2, verbose_name='Estado')),
                ('Descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('Precio', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Precio')),
                ('Cantidad', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Cantidad/Nro de Muestras')),
                ('FechaRegistro', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
            },
        ),
    ]
