# Generated by Django 2.2.6 on 2019-10-26 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0002_auto_20191026_0027'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='Foto',
            field=models.ImageField(blank=True, default='/non/newitem.png', null=True, upload_to='Items', verbose_name='Foto'),
        ),
    ]
