# Generated by Django 2.2.6 on 2019-10-27 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0003_producto_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='Foto',
            field=models.ImageField(blank=True, default='/non/newitem.jpg', null=True, upload_to='Items', verbose_name='Foto'),
        ),
    ]
