# Generated by Django 2.2.6 on 2019-10-27 02:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0005_producto_proveedoritem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='ProveedorItem',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='proveedores.Proveedor'),
        ),
    ]
