# Generated by Django 2.2.6 on 2019-10-28 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0006_auto_20191027_0228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='Cantidad',
            field=models.IntegerField(blank=True, null=True, verbose_name='Cantidad'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='Precio',
            field=models.FloatField(verbose_name='Precio'),
        ),
    ]
