# Generated by Django 2.2.7 on 2019-11-22 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0007_auto_20191028_2142'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='SerializeProducto',
            field=models.IntegerField(default=0, verbose_name='Serial'),
        ),
    ]
