# Generated by Django 2.2.7 on 2019-11-22 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0008_producto_serializeproducto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='SerializeProducto',
            field=models.IntegerField(default=0, verbose_name='Nro. de Producto'),
        ),
    ]
