# Generated by Django 2.2.7 on 2019-11-28 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0009_auto_20191122_0129'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='PrecioCompra',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True, verbose_name='Precio de Compra'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='Precio',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True, verbose_name='Precio de Venta'),
        ),
    ]
