# Generated by Django 2.2.6 on 2019-11-18 22:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Foto', models.ImageField(blank=True, default='/non/images.png', null=True, upload_to='Perfil', verbose_name='Foto')),
                ('movil', models.CharField(default='', max_length=20, verbose_name='Movil')),
                ('ChangePass', models.BooleanField(default=False, verbose_name='Clave Cambiada')),
                ('User', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Perfil',
                'verbose_name_plural': 'Perfiles',
            },
        ),
    ]
