version: "3.9"

services:
  db:
    image: mysql/mysql-server:5.7
    ports:
      - "3306:3306"
    env_file:
      - .env    
    volumes:
      - .:/code
    networks:
      - italmod-oms

  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    expose:
      - "8000"
    depends_on:
      - db
    env_file:
      - .env
    environment:
      - VIRTUAL_HOST=test.blux-in.com
      - VIRTUAL_PORT=8000
      - LETSENCRYPT_HOST=test.blux-in.com
      - LETSENCRYPT_EMAIL=lmendoza@blux-in.com
    networks:
      - italmod-oms

networks:
  italmod-oms:
    external:
      name: nginx-proxy
