# Generated by Django 2.2.4 on 2019-09-10 01:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
        ('general', '0002_moneda'),
    ]

    operations = [
        migrations.CreateModel(
            name='CotizacionCabecera',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ContSerializeQtn', models.IntegerField(default=0, verbose_name='Nro. Cotización')),
                ('SerializeQtn', models.IntegerField(default=0, verbose_name='Versión Cotización')),
                ('FechaCreacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('TiempoEntrega', models.CharField(blank=True, max_length=200, null=True, verbose_name='Tiempo de Entrega')),
                ('Asunto', models.CharField(max_length=200, verbose_name='Asunto de la Cotizacion')),
                ('Estado', models.IntegerField(choices=[(0, 'Anulado'), (1, 'Confirmado'), (2, 'Por Confirmar'), (3, 'Expirado')], default=2, verbose_name='Estado')),
                ('Descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('Descuento', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True, verbose_name='Precio')),
                ('FechaRegistro', models.DateTimeField(auto_now=True)),
                ('Cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='clientes.Clientes')),
                ('Moneda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='general.Moneda')),
            ],
            options={
                'verbose_name': 'Cotización',
                'verbose_name_plural': 'Cotización',
            },
        ),
    ]
