# Generated by Django 2.2.6 on 2019-10-27 02:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0006_auto_20191027_0228'),
        ('cotizaciones', '0002_auto_20191021_2332'),
    ]

    operations = [
        migrations.CreateModel(
            name='CuerpoCotizacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cabecera', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cotizaciones.CotizacionCabecera')),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='items.Producto')),
            ],
            options={
                'verbose_name': 'Cuerpo Cotizacion',
                'verbose_name_plural': 'Cuerpo de Cotizacion',
            },
        ),
    ]
