# Generated by Django 2.2.7 on 2019-11-23 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizaciones', '0004_productoqtn'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuerpocotizacion',
            name='cantidad',
            field=models.IntegerField(blank=True, null=True, verbose_name='Cantidad'),
        ),
        migrations.AddField(
            model_name='cuerpocotizacion',
            name='precio',
            field=models.FloatField(blank=True, null=True, verbose_name='Precio'),
        ),
        migrations.DeleteModel(
            name='productoQTN',
        ),
    ]
