# Generated by Django 2.2.7 on 2019-11-26 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizaciones', '0005_auto_20191123_0506'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuerpocotizacion',
            name='precio',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True, verbose_name='Precio'),
        ),
    ]
