# Generated by Django 2.2.7 on 2019-11-28 04:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
        ('cotizaciones', '0006_auto_20191126_0047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cotizacioncabecera',
            name='Estado',
            field=models.CharField(choices=[('COTIZACIÓN', 'COTIZACIÓN'), ('CONFIRMAR', 'CONFIRMAR'), ('ANULAR', 'ANULAR')], max_length=15, verbose_name='Estado'),
        ),
        migrations.CreateModel(
            name='ItemPago',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NombrePago', models.CharField(default='', max_length=500, verbose_name='Nombre del Pago')),
                ('FechaRegistro', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Registro')),
                ('NroPago', models.CharField(max_length=20, verbose_name='Número de Pago')),
                ('Estado', models.BooleanField(default=False, verbose_name='Estado del Item')),
                ('CodigoReferencia', models.CharField(blank=True, max_length=200, null=True, verbose_name='Código de Referencia')),
                ('NroTarjeta', models.CharField(blank=True, max_length=30, null=True, verbose_name='Últimos dígitos de la tarjeta')),
                ('FechaPago', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Pago')),
                ('Monto', models.FloatField(verbose_name='Monto')),
                ('EstadoPago', models.BooleanField(default=False, verbose_name='Estado del Pago')),
                ('CodigoPublico', models.CharField(max_length=128, verbose_name='Código Público')),
                ('CulqiStatus', models.CharField(default='', max_length=500, verbose_name='Código de Estado')),
                ('CulqiMessage', models.CharField(default='', max_length=1000, verbose_name='Mensaje de Pago')),
                ('CulqiRefCode', models.CharField(default='', max_length=500, verbose_name='Código Referencia Culqi')),
                ('CulqiAuthCode', models.CharField(default='', max_length=500, verbose_name='Código de Autorización Culqi')),
                ('CulqiFee', models.FloatField(default=0.0, verbose_name='Comision Culqi')),
                ('CulqiFeeTaxes', models.FloatField(default=0.0, verbose_name='Impuesto Comision Culqi ')),
                ('Cliente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='clientes.Clientes')),
                ('cuerpo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cotizaciones.CuerpoCotizacion')),
            ],
            options={
                'verbose_name': 'Pago Url',
                'verbose_name_plural': 'Pago Url',
            },
        ),
    ]
