# Generated by Django 2.2.7 on 2019-12-07 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizaciones', '0009_auto_20191206_2337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itempago',
            name='Monto',
            field=models.FloatField(default=0.0, verbose_name='Monto'),
        ),
    ]
