# Generated by Django 2.2.6 on 2019-10-29 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DatosEmpresa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NOmbre', models.CharField(max_length=200, verbose_name='Razón Social')),
                ('NickName', models.CharField(max_length=200, verbose_name='Nombre Comercial')),
                ('Direccion', models.CharField(max_length=500, verbose_name='Dirección')),
                ('Website', models.CharField(max_length=300, verbose_name='Website')),
                ('Mail', models.EmailField(max_length=300, verbose_name='Correo Electrónico')),
                ('RUC', models.CharField(max_length=30, verbose_name='RUC')),
            ],
            options={
                'verbose_name': 'Datos de la Empresa',
                'verbose_name_plural': 'Datos de la Empresa',
            },
        ),
    ]
