# Generated by Django 2.2.4 on 2019-09-03 01:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('general', '0002_moneda'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NombreContacto', models.CharField(default='', max_length=255, verbose_name='Nombres Contacto Cliente')),
                ('ApellidoContacto', models.CharField(default='', max_length=255, verbose_name='Apellidos Contacto Cliente')),
                ('NroDocumentoContacto', models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='Número Documento')),
                ('CorreoElectronicoContacto', models.CharField(max_length=300, verbose_name='Correo Electrónico')),
                ('MovilContacto', models.CharField(max_length=20, verbose_name='Teléfono Móvil')),
                ('LugarTrabajo', models.CharField(default='', max_length=20, verbose_name='Lugar de Trabajo')),
                ('Cargo', models.CharField(blank=True, default='', max_length=20, null=True, verbose_name='Cargo')),
                ('Principal', models.BooleanField(default=False, verbose_name='Contacto Principal')),
                ('TipoDocumentoContacto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='TipoDocumentoContacto', to='general.TipoDocumento')),
            ],
            options={
                'verbose_name': 'Contacto de Cliente',
                'verbose_name_plural': 'Contactos de Clientes',
            },
        ),
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('RazonSocial', models.CharField(default='', max_length=100, verbose_name='Razón Social')),
                ('Website', models.URLField(blank=True, null=True, verbose_name='WebSite')),
                ('CorreoElectronico', models.EmailField(blank=True, max_length=500, null=True, verbose_name='Correo Electrónico')),
                ('TipoPersona', models.IntegerField(choices=[(1, 'Persona Jurídica'), (2, 'Persona Natural con Negocio'), (3, 'Persona Natural sin Negocio')])),
                ('RUC', models.CharField(max_length=15, verbose_name='RUC')),
                ('DireccionLegal', models.CharField(max_length=500, verbose_name='Dirección Legal')),
                ('LegalName', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Nombres Representante Legal')),
                ('LegalLastName', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Apellidos Representante Legal')),
                ('NroDocumentoLegal', models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='Número Documento')),
                ('ContactoClientes', models.ManyToManyField(to='clientes.Contacto')),
                ('TipoDocumentoLegal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='TipoDocumentoLegal', to='general.TipoDocumento')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
            },
        ),
    ]
