# Generated by Django 2.2.4 on 2019-08-29 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TipoDocumento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(default='', max_length=200, verbose_name='Tipo de Documento')),
                ('Abreviatura', models.CharField(default='', max_length=200, verbose_name='Abreviatura')),
            ],
            options={
                'verbose_name': 'Tipo Documento',
                'verbose_name_plural': 'Tipos Documento',
            },
        ),
    ]
