# Generated by Django 2.2.4 on 2019-08-30 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Moneda',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Moneda', models.CharField(default='', max_length=100, verbose_name='Nombre Moneda')),
                ('Plural', models.CharField(default='', max_length=100, verbose_name='Nombre Moneda Plural')),
                ('Signo', models.CharField(default='', max_length=10, verbose_name='Signo')),
                ('Denominacion', models.CharField(default='', max_length=5, verbose_name='Denominacion')),
            ],
            options={
                'verbose_name': 'Moneda',
                'verbose_name_plural': 'Monedas',
            },
        ),
    ]
