# Generated by Django 2.2.6 on 2019-10-27 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proveedores', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='proveedor',
            name='Movil',
            field=models.CharField(blank=True, default='', max_length=9, null=True, verbose_name='Celular'),
        ),
    ]
