# Generated by Django 2.2.7 on 2019-11-28 15:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('proveedores', '0003_auto_20191027_0227'),
        ('items', '0010_auto_20191128_0531'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrdenCabecera',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ContSerializeQtn', models.IntegerField(default=0, verbose_name='Nro. Cotización')),
                ('SerializeQtn', models.IntegerField(default=0, verbose_name='Versión Cotización')),
                ('FechaCreacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('CondicionVenta', models.CharField(choices=[('CONTADO', 'CONTADO'), ('CREDITO', 'CREDITO'), ('CREDITO Y CONTADO', 'CREDITO Y CONTADO')], default='CONTADO', max_length=10)),
                ('Estado', models.BooleanField(default=False, verbose_name='Estado')),
                ('Proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proveedores.Proveedor')),
            ],
            options={
                'verbose_name': 'Orden de Compra',
                'verbose_name_plural': 'Orden de Compra',
            },
        ),
        migrations.CreateModel(
            name='OrdenCompraCierre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FacturaCompraFisico', models.FileField(default='/non/non.jpg', upload_to='Facturas/', verbose_name='Factura Fisico')),
                ('GuiadeRemisionFisico', models.FileField(default='/non/non.jpg', upload_to='guias/', verbose_name='Guia de Remisión Fisico')),
                ('CompraHead', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ordencompra.OrdenCabecera')),
            ],
            options={
                'verbose_name': 'CompraCierre',
                'verbose_name_plural': 'CompraCierre',
            },
        ),
        migrations.CreateModel(
            name='OrdenCompraBody',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Cantidad', models.IntegerField(blank=True, null=True, verbose_name='Cantidad')),
                ('CompraHead', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ordencompra.OrdenCabecera')),
                ('Item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='items.Producto')),
            ],
            options={
                'verbose_name': 'CompraBody',
                'verbose_name_plural': 'ComprasBody',
            },
        ),
    ]
