# Generated by Django 2.2.7 on 2019-11-28 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordencompra', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordencabecera',
            name='CondicionVenta',
            field=models.CharField(choices=[('CONTADO', 'CONTADO'), ('CREDITO', 'CREDITO'), ('CREDITO Y CONTADO', 'CREDITO Y CONTADO')], default='CONFIRMAR', max_length=10),
        ),
        migrations.AlterField(
            model_name='ordencabecera',
            name='Estado',
            field=models.CharField(choices=[('CONFIRMAR', 'CONFIRMAR'), ('FACTURADO', 'FACTURADO')], max_length=15, verbose_name='Estado'),
        ),
    ]
