# Generated by Django 2.2.7 on 2019-12-05 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordencompra', '0003_auto_20191128_1958'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordencabecera',
            name='CondicionVenta',
            field=models.CharField(choices=[('CONTADO', 'CONTADO'), ('CREDITO', 'CREDITO'), ('CREDITO Y CONTADO', 'CREDITO Y CONTADO')], default='CONFIRMAR', max_length=50),
        ),
        migrations.AlterField(
            model_name='ordencabecera',
            name='Estado',
            field=models.CharField(choices=[('CONFIRMAR', 'CONFIRMAR'), ('FACTURADO', 'FACTURADO'), ('ANULAR', 'ANULAR')], max_length=20, verbose_name='Estado'),
        ),
    ]
